# Generated by Django 2.2.16 on 2023-03-18 19:41

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_follow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follow",
            options={},
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                fields=("user", "author"), name="unique_follow"
            ),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.CheckConstraint(
                check=models.Q(
                    _negated=True,
                    user=django.db.models.expressions.F("author"),
                ),
                name="not_subscribe_yourself",
            ),
        ),
    ]
