# Generated by Django 2.2.16 on 2023-03-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0008_auto_20230318_2242"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="follow",
            name="unique_follow",
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                fields=("user", "author"), name="uq_user_author"
            ),
        ),
    ]
